"""Folioman API Client Package."""

from folioman_intelligence.clients.folioman.auth import JWTAuthManager
from folioman_intelligence.clients.folioman.client import FoliomanClient
from folioman_intelligence.clients.folioman.errors import (
    FoliomanAPIError,
    FoliomanAuthError,
    FoliomanError,
    FoliomanNotFoundError,
)
from folioman_intelligence.clients.folioman.models import (
    AllocationBucket,
    AssetMixRow,
    CapitalGainRow,
    CapitalGainsFyPoint,
    CapitalGainsReport,
    ConfiguredDate,
    ConfiguredDatetime,
    ConfiguredDecimal,
    FolioBalance,
    Holding,
    Investor,
    InvestorDetail,
    NavPoint,
    PeriodReturn,
    PortfolioSummary,
    SchemeDetail,
    SchemeRef,
    Transaction,
    ValuationStatus,
    ValueSeries,
    ValueSeriesPoint,
)

__all__ = [
    "FoliomanClient",
    "FoliomanError",
    "FoliomanAuthError",
    "FoliomanNotFoundError",
    "FoliomanAPIError",
    "JWTAuthManager",
    "Investor",
    "InvestorDetail",
    "Holding",
    "SchemeRef",
    "NavPoint",
    "FolioBalance",
    "SchemeDetail",
    "Transaction",
    "AssetMixRow",
    "AllocationBucket",
    "PeriodReturn",
    "PortfolioSummary",
    "ValueSeriesPoint",
    "ValueSeries",
    "ValuationStatus",
    "CapitalGainRow",
    "CapitalGainsReport",
    "CapitalGainsFyPoint",
    "ConfiguredDecimal",
    "ConfiguredDate",
    "ConfiguredDatetime",
]
