"""Common Logging and Event Streaming Infrastructure for Folioman Agents.

Provides uniform logging, terminal output formatting, token streaming,
and execution helpers for current and future autonomous agents.
"""

from __future__ import annotations

import datetime
from decimal import Decimal
import json
import logging
import sys
from typing import Any, TextIO, TypeVar

# Type variable for AgentResponse and its subclasses
T = TypeVar("T", bound="AgentResponse")


def configure_utf8_stdout() -> None:
    """Ensure console supports UTF-8 characters (e.g. ₹ currency symbol) on Windows."""
    if hasattr(sys.stdout, "reconfigure"):
        try:
            sys.stdout.reconfigure(encoding="utf-8")
        except Exception:
            pass


# Ensure UTF-8 configuration on module import
configure_utf8_stdout()


def safe_format(val: Any, indent: int = 2) -> str:
    """Format inputs or outputs into clean, readable JSON or string representation."""
    if isinstance(val, (dict, list)):
        return json.dumps(val, indent=indent, default=str)
    if isinstance(val, str):
        try:
            parsed = json.loads(val)
            return json.dumps(parsed, indent=indent, default=str)
        except Exception as e:
            print(
                f"[SAFE FORMAT] json load failed due to : {e} : {e.__class__.__name__}"
            )
            pass
        try:
            safe_env = {
                "Decimal": Decimal,
                "datetime": datetime,
                "date": datetime.date,
            }
            parsed = eval(val, {"__builtins__": {}}, safe_env)
            if isinstance(parsed, (dict, list)):
                return json.dumps(parsed, indent=indent, default=str)
        except Exception as e:
            print(
                f"[SAFE FORMAT] safe env evaluation failed due to : {e} : {e.__class__.__name__}"
            )
            pass
    return str(val) if val is not None else ""


def parse_output_value(val: Any) -> Any:
    """Parse raw output or string into a Python dict/list if applicable."""
    if isinstance(val, (dict, list)):
        return val
    if isinstance(val, str):
        try:
            return json.loads(val)
        except Exception as e:
            print(
                f"[parsed_output_name] json load failed due to : {e} : {e.__class__.__name__}"
            )
            pass
        try:
            safe_env = {
                "Decimal": Decimal,
                "datetime": datetime,
                "date": datetime.date,
            }
            parsed = eval(val, {"__builtins__": {}}, safe_env)
            if isinstance(parsed, (dict, list)):
                return parsed
        except Exception as e:
            print(
                f"[parsed_output_name] safe env eval failed due to : {e} : {e.__class__.__name__}"
            )
            pass
    return val


def extract_text_chunk(chunk_content: Any) -> str:
    """Extract plain text generated by the model from a stream chunk, ignoring tool-call tokens."""
    if isinstance(chunk_content, str):
        return chunk_content
    if isinstance(chunk_content, list):
        text_parts: list[str] = []
        for item in chunk_content:
            if isinstance(item, str):
                text_parts.append(item)
            elif isinstance(item, dict) and item.get("type") == "text":
                text_parts.append(item.get("text", ""))
        return "".join(text_parts)
    return ""


def extract_final_text(message: Any) -> str:
    """Extract final text from an AIMessage or ChatResult."""
    if not message:
        return ""
    content = getattr(message, "content", message)
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        text_parts: list[str] = []
        for item in content:
            if isinstance(item, str):
                text_parts.append(item)
            elif isinstance(item, dict) and item.get("type") == "text":
                text_parts.append(item.get("text", ""))
        return "".join(text_parts)
    return str(content) if content is not None else ""


class AgentResponse(dict):
    """Base response returned by agent executions.

    Acts as a dictionary containing 'content' and 'tool_calls',
    while supporting direct property access (.content, .tool_calls)
    and clean string representation.
    """

    @property
    def content(self) -> str:
        return self.get("content", "")

    @property
    def tool_calls(self) -> list[dict[str, Any]]:
        return self.get("tool_calls", [])

    def __str__(self) -> str:
        return self.content


class AgentRunLogger:
    """Common logger and event handler for autonomous agent execution.

    Handles real-time formatting, terminal stream presentation, and standard
    logging for tool execution, tool output, and LLM token streaming across
    all Folioman agents.
    """

    def __init__(
        self,
        stream: TextIO | None = sys.stdout,
        verbose: bool = True,
        logger: logging.Logger | None = None,
        agent_name: str | None = None,
        separator_char: str = "=",
        sub_separator_char: str = "-",
        line_width: int = 70,
    ) -> None:
        self.stream = stream
        self.verbose = verbose
        self.logger = logger or logging.getLogger(__name__)
        self.agent_name = agent_name
        self.separator = separator_char * line_width
        self.sub_separator = sub_separator_char * line_width
        self.streaming_llm_active = False

    def reset(self) -> None:
        """Reset internal streaming state between runs."""
        self.streaming_llm_active = False

    def _print(self, text: str = "") -> None:
        """Print text to the configured output stream if verbose."""
        if self.verbose and self.stream is not None:
            print(text, file=self.stream)

    def log_tool_start(self, name: str, tool_input: Any) -> None:
        """Log and display the initiation of a tool call."""
        if self.streaming_llm_active:
            self.end_llm_stream()

        formatted_input = safe_format(tool_input)

        self._print(f"\n{self.separator}")
        self._print(f"🛠️  [TOOL CALL] {name}")
        self._print(self.sub_separator)
        self._print(f"Arguments:\n{formatted_input}")
        self._print(f"{self.separator}\n")

        prefix = f"[{self.agent_name}] " if self.agent_name else ""
        self.logger.debug(
            "%s🛠️  [TOOL CALL] %s with arguments:\n%s", prefix, name, formatted_input
        )

    def log_tool_end(self, name: str, raw_output: Any) -> Any:
        """Log and display the completion of a tool call.

        Extracts the output value, prints the formatted result, and returns
        the parsed Python value for recording.
        """
        if self.streaming_llm_active:
            self.end_llm_stream()

        # Extract content if wrapped in a ToolMessage or artifact
        if hasattr(raw_output, "artifact") and raw_output.artifact is not None:
            output_val = raw_output.artifact
        elif hasattr(raw_output, "content"):
            output_val = raw_output.content
        else:
            output_val = raw_output

        formatted_output = safe_format(output_val)

        self._print(f"\n{self.separator}")
        self._print(f"📦 [TOOL OUTPUT] {name}")
        self._print(self.sub_separator)
        self._print(f"Output:\n{formatted_output}")
        self._print(f"{self.separator}\n")

        prefix = f"[{self.agent_name}] " if self.agent_name else ""
        self.logger.debug("%s📦 [TOOL OUTPUT] %s:\n%s", prefix, name, formatted_output)

        return parse_output_value(output_val)

    def log_llm_chunk(self, chunk: Any) -> str:
        """Process and stream an LLM response chunk.

        Displays the LLM response header on the first token, streams text to the
        output stream, and returns the extracted text string.
        """
        if not chunk:
            return ""

        content = getattr(chunk, "content", chunk)
        text = extract_text_chunk(content)
        if text:
            if not self.streaming_llm_active:
                self._print(f"\n{self.separator}")
                self._print("🤖 [LLM RESPONSE]")
                self._print(self.sub_separator)
                self.streaming_llm_active = True

            if self.verbose and self.stream is not None:
                self.stream.write(text)
                self.stream.flush()

        return text

    def end_llm_stream(self) -> None:
        """Close the active LLM response stream display if open."""
        if self.streaming_llm_active:
            self._print(f"\n{self.separator}\n")
            self.streaming_llm_active = False

    def log_model_end(self, output: Any, has_generated_chunks: bool) -> str:
        """Handle completion of chat model generation.

        Closes stream display and extracts fallback text if tokens were not streamed.
        """
        self.end_llm_stream()

        if not has_generated_chunks and output:
            msg = None
            if hasattr(output, "generations") and output.generations:
                msg = output.generations[0].message
            elif hasattr(output, "content"):
                msg = output
            if msg:
                extracted = extract_final_text(msg)
                if extracted:
                    prefix = f"[{self.agent_name}] " if self.agent_name else ""
                    self.logger.debug(
                        "%s🤖 [LLM FALLBACK OUTPUT] %s", prefix, extracted
                    )
                    return extracted
        return ""

    def handle_event(
        self,
        event: dict[str, Any],
        recorded_tool_calls: list[dict[str, Any]],
        generated_text_chunks: list[str],
    ) -> None:
        """Handle a single LangChain astream_events event.

        Updates recorded tool calls and text chunks accordingly.
        """
        event_type = event.get("event")
        name = event.get("name", "")
        data = event.get("data", {})

        if event_type == "on_tool_start":
            tool_input = data.get("input")
            self.log_tool_start(name, tool_input)
            recorded_tool_calls.append(
                {
                    "name": name,
                    "input": tool_input,
                    "output": None,
                }
            )

        elif event_type == "on_tool_end":
            raw_output = data.get("output")
            parsed_val = self.log_tool_end(name, raw_output)

            # Assign output to the matching tool call
            if recorded_tool_calls and recorded_tool_calls[-1]["name"] == name:
                recorded_tool_calls[-1]["output"] = parsed_val
            else:
                for tc in reversed(recorded_tool_calls):
                    if tc["name"] == name and tc["output"] is None:
                        tc["output"] = parsed_val
                        break

        elif event_type == "on_chat_model_stream":
            chunk = data.get("chunk")
            text = self.log_llm_chunk(chunk)
            if text:
                generated_text_chunks.append(text)

        elif event_type == "on_chat_model_end":
            fallback_text = self.log_model_end(
                data.get("output"),
                has_generated_chunks=bool(generated_text_chunks),
            )
            if fallback_text:
                generated_text_chunks.append(fallback_text)

    async def run(
        self,
        agent: Any,
        question: str | dict[str, Any],
        response_cls: type[T] = AgentResponse,
    ) -> T:
        """Execute an agent query using this logger instance."""
        return await run_agent(
            agent=agent,
            question=question,
            logger=self,
            response_cls=response_cls,
        )


async def run_agent(
    agent: Any,
    question: str | dict[str, Any],
    *,
    logger: AgentRunLogger | None = None,
    response_cls: type[T] = AgentResponse,
) -> T:
    """Execute an agent query using unified event streaming and logging.

    Args:
        agent: The agent runnable supporting astream_events.
        question: The user query string or a message dictionary.
        logger: Optional AgentRunLogger instance. If None, a default logger is used.
        response_cls: The response class to instantiate (defaults to AgentResponse).

    Returns:
        An instance of response_cls containing 'content' and 'tool_calls'.
    """
    if isinstance(question, str):
        messages = {
            "messages": [
                {
                    "role": "user",
                    "content": question,
                }
            ]
        }
    else:
        messages = question

    active_logger = logger if logger is not None else AgentRunLogger()
    active_logger.reset()

    recorded_tool_calls: list[dict[str, Any]] = []
    generated_text_chunks: list[str] = []

    async for event in agent.astream_events(input=messages):
        active_logger.handle_event(event, recorded_tool_calls, generated_text_chunks)

    active_logger.end_llm_stream()

    final_content = "".join(generated_text_chunks).strip()

    return response_cls(
        {
            "content": final_content,
            "tool_calls": recorded_tool_calls,
        }
    )
