import datetime
from decimal import Decimal
import json
import sys

from deepagents import create_deep_agent
from langchain_openai import ChatOpenAI

from folioman_intelligence.config import llm_settings
from folioman_intelligence.tools.portfolio import portfolio_tools

# Ensure console supports UTF-8 characters (e.g. ₹ currency symbol) on Windows
if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass


# TODO: Introduce LLMLite so models can be swapped easily.
# ### Chat Model
model_name = getattr(
    llm_settings, "MODEL_NAME", getattr(llm_settings, "model_name", "gpt-4")
)
chat_model = ChatOpenAI(
    model=model_name,
    api_key=llm_settings.api_key,
    temperature=llm_settings.temperature,
    use_responses_api=True,
)


# ## Agent ###
SYSTEM_PROMPT = """
You are a portfolio intelligence agent.

Your job is to analyze the user's investment portfolio using the tools available to you.

## Core rules

1. Use tools to retrieve portfolio data and analytics when answering portfolio-related questions.
2. Never invent portfolio data, holdings, returns, or metrics.
3. Treat values returned by analytics tools as the source of truth for calculations.
4. Do not perform financial calculations yourself when the required metric is available through a tool.
5. You may combine information from multiple tools to investigate a question.
6. Distinguish clearly between:
    - Facts: directly supported by portfolio data.
    - Observations: conclusions derived from those facts.
7. If the available data is insufficient to answer a question, say so clearly.
8. Do not assume information that is not available in the portfolio data.
9. Do not execute transactions or modify the user's portfolio.
10. Do not provide personalized buy/sell instructions. Focus on analysis, risks, observations, and relevant information.

## Investigation behavior

For simple questions, use the minimum tools necessary.

For questions requiring investigation:
- Identify what information is needed.
- Call the relevant tools.
- Combine the returned information.
- Form your conclusion from the available evidence.

Do not call tools unnecessarily.

## Response style

Be concise and structured.

Prefer:

- Summary
- Key findings
- Supporting numbers
- Areas worth examining

When presenting a conclusion, explain the relevant evidence behind it.

Never fabricate certainty when the available data is incomplete.


## Tool selection

Choose tools based on the user's question.

- Use `get_portfolio_analysis` for questions about:
    - portfolio value
    - invested amount
    - returns
    - holdings summary
    - allocation
    - general portfolio overview

- Use `get_risk_analysis` only when the question specifically involves:
    - risk
    - concentration
    - volatility
    - drawdown
    - diversification
    - risk exposure

- Use `get_holdings` when the question requires examining individual holdings.

Do not call a tool simply because it is available.

Use the minimum number of tools required to answer the question.

For a question that can be answered from one tool, call only that tool.

For a general portfolio question, do not automatically call the risk analysis tool.

For a risk question, do not automatically call the general portfolio analysis tool unless information from it is actually required.
"""


agent = create_deep_agent(
    model=chat_model,
    tools=portfolio_tools,
    system_prompt=SYSTEM_PROMPT,
)


def _safe_format(val, indent: int = 2) -> str:
    """Format inputs or outputs into clean, readable JSON or string representation."""
    if isinstance(val, (dict, list)):
        return json.dumps(val, indent=indent, default=str)
    if isinstance(val, str):
        try:
            parsed = json.loads(val)
            return json.dumps(parsed, indent=indent, default=str)
        except Exception:
            pass
        try:
            safe_env = {"Decimal": Decimal, "datetime": datetime}
            parsed = eval(val, {"__builtins__": {}}, safe_env)
            if isinstance(parsed, (dict, list)):
                return json.dumps(parsed, indent=indent, default=str)
        except Exception:
            pass
    return str(val) if val is not None else ""


def _parse_output_value(val):
    """Parse raw output or string into a Python dict/list if applicable."""
    if isinstance(val, (dict, list)):
        return val
    if isinstance(val, str):
        try:
            return json.loads(val)
        except Exception:
            pass
        try:
            safe_env = {"Decimal": Decimal, "datetime": datetime}
            parsed = eval(val, {"__builtins__": {}}, safe_env)
            if isinstance(parsed, (dict, list)):
                return parsed
        except Exception:
            pass
    return val


def _extract_text_chunk(chunk_content) -> str:
    """Extract plain text generated by the model from a stream chunk, ignoring tool-call tokens."""
    if isinstance(chunk_content, str):
        return chunk_content
    if isinstance(chunk_content, list):
        text_parts = []
        for item in chunk_content:
            if isinstance(item, str):
                text_parts.append(item)
            elif isinstance(item, dict) and item.get("type") == "text":
                text_parts.append(item.get("text", ""))
        return "".join(text_parts)
    return ""


def _extract_final_text(message) -> str:
    """Extract final text from an AIMessage or ChatResult."""
    if not message:
        return ""
    content = getattr(message, "content", message)
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        text_parts = []
        for item in content:
            if isinstance(item, str):
                text_parts.append(item)
            elif isinstance(item, dict) and item.get("type") == "text":
                text_parts.append(item.get("text", ""))
        return "".join(text_parts)
    return str(content) if content is not None else ""


class PortfolioAgentResponse(dict):
    """Response returned by ask_portfolio_agent.

    Acts as a dictionary containing 'content' and 'tool_calls',
    while supporting direct property access (.content, .tool_calls)
    and clean string representation.
    """

    @property
    def content(self) -> str:
        return self.get("content", "")

    @property
    def tool_calls(self) -> list[dict]:
        return self.get("tool_calls", [])

    def __str__(self) -> str:
        return self.content


async def ask_portfolio_agent(question: str) -> PortfolioAgentResponse:
    messages = {
        "messages": [
            {
                "role": "user",
                "content": question,
            }
        ]
    }

    recorded_tool_calls: list[dict] = []
    streaming_llm_active = False
    generated_text_chunks: list[str] = []

    separator = "=" * 70
    sub_separator = "-" * 70

    async for event in agent.astream_events(input=messages):
        event_type = event.get("event")
        name = event.get("name")
        data = event.get("data", {})

        if event_type == "on_tool_start":
            if streaming_llm_active:
                print(f"\n{separator}\n")
                streaming_llm_active = False

            tool_input = data.get("input")
            formatted_input = _safe_format(tool_input)
            print(f"\n{separator}")
            print(f"🛠️  [TOOL CALL] {name}")
            print(sub_separator)
            print(f"Arguments:\n{formatted_input}")
            print(f"{separator}\n")

            recorded_tool_calls.append(
                {
                    "name": name,
                    "input": tool_input,
                    "output": None,
                }
            )

        elif event_type == "on_tool_end":
            if streaming_llm_active:
                print(f"\n{separator}\n")
                streaming_llm_active = False

            raw_output = data.get("output")

            # Extract content if wrapped in a ToolMessage
            if hasattr(raw_output, "artifact") and raw_output.artifact is not None:
                output_val = raw_output.artifact
            elif hasattr(raw_output, "content"):
                output_val = raw_output.content
            else:
                output_val = raw_output

            formatted_output = _safe_format(output_val)

            print(f"\n{separator}")
            print(f"📦 [TOOL OUTPUT] {name}")
            print(sub_separator)
            print(f"Output:\n{formatted_output}")
            print(f"{separator}\n")

            if recorded_tool_calls and recorded_tool_calls[-1]["name"] == name:
                recorded_tool_calls[-1]["output"] = _parse_output_value(output_val)

        elif event_type == "on_chat_model_stream":
            chunk = data.get("chunk")
            if chunk:
                text = _extract_text_chunk(getattr(chunk, "content", None))
                if text:
                    if not streaming_llm_active:
                        print(f"\n{separator}")
                        print("🤖 [LLM RESPONSE]")
                        print(sub_separator)
                        streaming_llm_active = True
                    sys.stdout.write(text)
                    sys.stdout.flush()
                    generated_text_chunks.append(text)

        elif event_type == "on_chat_model_end":
            if streaming_llm_active:
                print(f"\n{separator}\n")
                streaming_llm_active = False

            # Fallback if text wasn't captured in stream chunks
            out = data.get("output")
            if not generated_text_chunks and out:
                msg = None
                if hasattr(out, "generations") and out.generations:
                    msg = out.generations[0].message
                elif hasattr(out, "content"):
                    msg = out
                if msg:
                    extracted = _extract_final_text(msg)
                    if extracted:
                        generated_text_chunks.append(extracted)

    if streaming_llm_active:
        print(f"\n{separator}\n")

    final_content = "".join(generated_text_chunks).strip()

    return PortfolioAgentResponse(
        {
            "content": final_content,
            "tool_calls": recorded_tool_calls,
        }
    )
